//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace course1._0
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class myCreatePO_projectEntities : DbContext
    {
        public myCreatePO_projectEntities()
            : base("name=myCreatePO_projectEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Т_ВидыРабот> Т_ВидыРабот { get; set; }
        public virtual DbSet<Т_Договора> Т_Договора { get; set; }
        public virtual DbSet<Т_Должность> Т_Должность { get; set; }
        public virtual DbSet<Т_Клиент> Т_Клиент { get; set; }
        public virtual DbSet<Т_Кураторы> Т_Кураторы { get; set; }
        public virtual DbSet<Т_Штат_сотрудников> Т_Штат_сотрудников { get; set; }
        public virtual DbSet<Т_Языки_прог> Т_Языки_прог { get; set; }
        public virtual DbSet<Login> Login { get; set; }
        public virtual DbSet<З_Договора_Запрос> З_Договора_Запрос { get; set; }
        public virtual DbSet<Т_Договор_Этапы> Т_Договор_Этапы { get; set; }
        public virtual DbSet<Т_Договора_Архив> Т_Договора_Архив { get; set; }
    }
}
