//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace course1._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class З_Договора_Запрос
    {
        public int C__Договора { get; set; }
        public string Название_договора { get; set; }
        public string Этапы_разработки { get; set; }
        public string ФИО { get; set; }
        public Nullable<System.DateTime> Дата_составления { get; set; }
        public Nullable<int> Колво_дней { get; set; }
        public Nullable<System.DateTime> Плановая_дата { get; set; }
        public string Фактическа_Дата { get; set; }
        public string Примечание { get; set; }
    }
}
