//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace course1._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class Т_Договора_Архив
    {
        public int C__Договора { get; set; }
        public string Название_договора { get; set; }
        public Nullable<int> Куратор_проекта { get; set; }
        public Nullable<int> ФИО_Клиента { get; set; }
        public Nullable<System.DateTime> Дата_составления { get; set; }
        public Nullable<int> Колво_дней { get; set; }
        public Nullable<System.DateTime> Плановая_дата { get; set; }
        public string Фактическа_Дата { get; set; }
        public string Примечание { get; set; }
        public Nullable<int> Язык_разработки { get; set; }
        public string Штраф { get; set; }
    }
}
