//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace course1._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class Т_ВидыРабот
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Т_ВидыРабот()
        {
            this.Т_Договор_Этапы = new HashSet<Т_Договор_Этапы>();
        }
    
        public int ID_Работы { get; set; }
        public string Этапы_разработки { get; set; }
        public Nullable<int> Нормо_часов { get; set; }
        public string Стоимость_часа_руб { get; set; }
        public Nullable<decimal> Сумма_руб { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Т_Договор_Этапы> Т_Договор_Этапы { get; set; }
    }
}
