//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace course1._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class Т_Клиент
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Т_Клиент()
        {
            this.Т_Договора = new HashSet<Т_Договора>();
        }
    
        public int ID_Клиента { get; set; }
        public byte[] Фото { get; set; }
        public string ФИО { get; set; }
        public string Адрес { get; set; }
        public string Реквизиты_банка { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Т_Договора> Т_Договора { get; set; }
    }
}
