//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace course1._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class Т_Штат_сотрудников
    {
        public int ID_сотрудника { get; set; }
        public Nullable<int> ID_Куратора { get; set; }
        public string ФИО { get; set; }
        public Nullable<int> Должность { get; set; }
        public Nullable<int> Язык_Программирования { get; set; }
    
        public virtual Т_Кураторы Т_Кураторы { get; set; }
        public virtual Т_Языки_прог Т_Языки_прог { get; set; }
    }
}
